Translate Advanced Guides > Forwarding Refs
reactjs/ko.reactjs.org pull request #260
Opened 2020-10-30 13:27 UTC by hapumee

Note to Hacktoberfest 🎃 participants:

While we appreciate the enthusiasm, we are experiencing a high volume of drive-by pull requests (one-line changes, README tweaks, etc.). Please remember that hundreds of people are subscribed to this repo and will receive notifications for these PRs. Spam submissions will be closed and won't count towards your Hacktoberfest goals.

Please search for issues tagged [`good first issue`][gfi] or [`hacktoberfest`][hacktoberfest] to find things to work on.

You can also search [all of GitHub][all].

[gfi]: https://github.com/reactjs/reactjs.org/issues?q=is%3Aissue+is%3Aopen+label%3A"good+first+issue"
[hacktoberfest]: https://github.com/reactjs/reactjs.org/issues?q=is%3Aissue+is%3Aopen+label%3A"good+first+issue"
[all]: https://github.com/search?q=is%3Aissue+hacktoberfest

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2021-01-29 14:17 UTC, hg-pyun requested changes

2021-01-29 14:17 UTC, hg-pyun commented on content/docs/forwarding-refs.md
> +ref 전달은 컴포넌트를 통해 자식 중 하나에 [ref](/docs/refs-and-the-dom.html)를 자동으로 전달하는 기법입니다. 이것은 일반적으로 애플리케이션 대부분의 컴포넌트에 필요하지는 않습니다. 그렇지만, 특히 재사용 가능한 컴포넌트 라이브러리와 같은 어떤 컴포넌트에서는 유용할 수 있습니다. 가장 보편적인 시나리오를 아래에 설명하겠습니다
아래와 같이 고쳐도 같은 의미를 나타낼 것 같습니다.
`이것은 일반적으로` -> `일반적으로`

2021-01-29 14:17 UTC, hg-pyun commented on content/docs/forwarding-refs.md
> +"logProps" HOC는 모든 `props`를 래핑하는 컴포넌트로 전달하므로 렌더링 된 결과가 동일하게 됩니다. 예를 들어, 이 HOC를 사용해서 "fancy button" 컴포넌트로 전달하는 모든 props를 로깅 할 수 있습니다.
로깅은 그대로 사용하는게 좋을까요? 적절한 한국어로 `추적` 정도는 어떨까 제안해봅니다.

2021-01-29 14:17 UTC, hg-pyun commented on content/docs/forwarding-refs.md
> +래핑하는 컴포넌트를 포함하도록 함수의 `displayName` 속성을 설정할 수도 있습니다.
래핑도 적절한 한국어로 대체해보는걸 고민해보면 좋을 듯 합니다.

#### ex
```
감싸고 있는 컴포넌트~~
```

2021-01-30 10:27 UTC, hapumee commented on content/docs/forwarding-refs.md
> +ref 전달은 컴포넌트를 통해 자식 중 하나에 [ref](/docs/refs-and-the-dom.html)를 자동으로 전달하는 기법입니다. 이것은 일반적으로 애플리케이션 대부분의 컴포넌트에 필요하지는 않습니다. 그렇지만, 특히 재사용 가능한 컴포넌트 라이브러리와 같은 어떤 컴포넌트에서는 유용할 수 있습니다. 가장 보편적인 시나리오를 아래에 설명하겠습니다
`일반적으로` 로 변경했습니다.

2021-01-30 10:37 UTC, hapumee commented on content/docs/forwarding-refs.md
> +"logProps" HOC는 모든 `props`를 래핑하는 컴포넌트로 전달하므로 렌더링 된 결과가 동일하게 됩니다. 예를 들어, 이 HOC를 사용해서 "fancy button" 컴포넌트로 전달하는 모든 props를 로깅 할 수 있습니다.
`logging`이 뭔가를 계속 남긴다는 의미로 `기록`은 어색할까요?

2021-01-30 10:38 UTC, hapumee commented on content/docs/forwarding-refs.md
> +래핑하는 컴포넌트를 포함하도록 함수의 `displayName` 속성을 설정할 수도 있습니다.
`감싸고 있는 컴포넌트` 좋은 것 같습니다. `감싸고 있는 컴포넌트`로 수정했습니다. : )

2021-01-30 12:51 UTC, hg-pyun commented on content/docs/forwarding-refs.md
> +"logProps" HOC는 모든 `props`를 래핑하는 컴포넌트로 전달하므로 렌더링 된 결과가 동일하게 됩니다. 예를 들어, 이 HOC를 사용해서 "fancy button" 컴포넌트로 전달하는 모든 props를 로깅 할 수 있습니다.
@hapumee 좋습니다! 기록이 더 좋을 것 같군요.

2021-01-30 12:52 UTC, hg-pyun commented on content/docs/forwarding-refs.md
> +래핑하는 컴포넌트를 포함하도록 함수의 `displayName` 속성을 설정할 수도 있습니다.
@hapumee push가 안된 것 같은데, 확인 부탁드립니다.

2021-01-30 13:11 UTC, hapumee commented on content/docs/forwarding-refs.md
> +"logProps" HOC는 모든 `props`를 래핑하는 컴포넌트로 전달하므로 렌더링 된 결과가 동일하게 됩니다. 예를 들어, 이 HOC를 사용해서 "fancy button" 컴포넌트로 전달하는 모든 props를 로깅 할 수 있습니다.
`기록`으로 변경했습니다. : )

2021-01-30 13:11 UTC, hapumee commented on content/docs/forwarding-refs.md
> +래핑하는 컴포넌트를 포함하도록 함수의 `displayName` 속성을 설정할 수도 있습니다.
@hg-pyun 님, 커맨트 내용을 수정하고 push 했습니다.

2021-02-11 13:37 UTC, hg-pyun approved these changes
LGTM

2021-02-11 13:38 UTC, merged

2021-02-14 02:22 UTC, hapumee commented
@hg-pyun 님, 그런데 한 가지 번역이 되지 않은 곳이 있는데요, 타이틀이요.  
제목을 간과했네요. T.T
번역해야 하지 않을까요?

https://ko.reactjs.org/docs/forwarding-refs.html

2021-02-14 13:47 UTC, hg-pyun commented
@hapumee 오.. 그렇군요. 다른 PR로 보내주시면 좋을 것 같습니다.