cross-origin-errors kr translate
reactjs/ko.reactjs.org pull request #380
Opened 2021-12-07 22:31 UTC by de24world

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

처음으로 번역 작업 참여해보는데요. 부족한점이 많이 있을거 같은데, origin 관련해서 원본 그대로 둘지 아니면 직역을 할지 등등 피드백 부탁드립니다

2021-12-08 01:09 UTC, alstn2468 reviewed
개인적으로 백틱 안에 있는 용어들은 번역하지 않는게 조금 더 매끄러울 것 같다는 생각이 듭니다!

2021-12-08 01:09 UTC, alstn2468 commented on content/docs/cross-origin-errors.md
> +CDN에서 리액트(혹은 오류를 발생시킬 수 있는 다른 라이브러리)를 로딩할 때, `<script>` 태그에 [`크로스오리진`](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes) 속성을 추가하세요:
크로스 오리진은 번역하지 않는게 맞을 것 같습니다.

2021-12-08 01:09 UTC, alstn2468 commented on content/docs/cross-origin-errors.md
> +CDN에서 리액트(혹은 오류를 발생시킬 수 있는 다른 라이브러리)를 로딩할 때, `<script>` 태그에 [`크로스오리진`](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes) 속성을 추가하세요:
attribute는 어트리뷰트로 번역하기로 용어집에 있었던 것 같습니다!

2021-12-08 01:09 UTC, alstn2468 commented on content/docs/cross-origin-errors.md
> +일부 자바스크립트 번들러는 개발 중에 `eval`문으로 코드를 래핑 되어 있을 수 있습니다. (예를 들어 웹팩은 [`devtool`](https://webpack.js.org/configuration/devtool/)이 "eval"이라는 단어가 포함된 값으로 설정된 경우 이 작업을 수행합니다) 이로 인해 크로스-오리진 오류로 처리될 수 있습니다.
래핑 -> 감싸다 괜찮을 것 같은데 어떻게 생각하시나요?

2021-12-08 01:09 UTC, alstn2468 commented on content/docs/cross-origin-errors.md
> +웹팩을 사용하는 경우, 이러한 문제를 피하기 위해서 개발 시에 `cheap-module-source-map` 설장하는 것을 추천합니다.
오타 있습니다. 설장 -> 설정

2021-12-08 01:09 UTC, alstn2468 commented on content/docs/cross-origin-errors.md
> +애플리케이션이 여러 번들로 분할된 경우 JSONP를 사용하여 로드될 수 있습니다. 이로 인해 번들 된 코드가 크로스-오리진 오류로 처리될 수도 있습니다.
번들 된 -> 번들링 된 어떨까요?

2021-12-08 09:52 UTC, x86chi requested changes

2021-12-08 09:52 UTC, x86chi commented on content/docs/cross-origin-errors.md
> +웹팩을 사용하는 경우, 이러한 문제를 피하기 위해서 개발 시에 `cheap-module-source-map` 설장하는 것을 추천합니다.
```suggestion
웹팩을 사용하는 경우, 이러한 문제를 피하고자 개발 시에 `cheap-module-source-map` 설정하는 것을 추천합니다.
```

> 영어의 영향으로 '-기 위해'를 많이 쓰는 예가 있습니다. 우리말에서 의도를 나타내는 어미는 '-려고'나 '-고자'로 쓸 수 있습니다.

[부산대 맞춤법 검사기](https://speller.cs.pusan.ac.kr/) 결과를 참고했습니다.

2021-12-08 09:52 UTC, x86chi commented on content/docs/cross-origin-errors.md
> +이러한 문제를 해결하려면, 개발 시에 [`크로스오리진로딩`](https://webpack.js.org/configuration/output/#output-crossoriginloading) 설정을 사용하여 JSOPN 요청에 대해 생성된 `<script>` 태그에 `크로스오리진` 속성을 추가하세요.
```suggestion
이러한 문제를 해결하려면, 개발 시에 [`crossOriginLoading`](https://webpack.js.org/configuration/output/#output-crossoriginloading) 설정을 사용하여 JSOPN 요청에 대해 생성된 `<script>` 태그에 `crossOriginLoading` 속성을 추가하세요.
```

번역하면 안되는 고유한 키워드입니다.

2021-12-09 01:37 UTC, x86chi submitted a review, later dismissed

2021-12-09 02:12 UTC, alstn2468 submitted a review, later dismissed

2021-12-09 17:18 UTC, gnujoow reviewed
PR 감사합니다.

2021-12-09 17:18 UTC, gnujoow commented on content/docs/cross-origin-errors.md
> +### 웹팩 {#webpack}
```suggestion
### Webpack {#webpack}
```
https://github.com/reactjs/ko.reactjs.org/issues/2#issuecomment-461709467

2021-12-10 06:20 UTC, gnujoow approved these changes

2021-12-10 14:54 UTC, hg-pyun approved these changes
LGTM

2021-12-12 13:28 UTC, merged

2021-12-12 13:28 UTC, taehwanno commented
기여해주셔서 감사합니다!