Translate: 'extracting state logic into a reducer'
reactjs/ko.reactjs.org pull request #391
Opened 2021-12-12 06:53 UTC by jinsunee

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [x] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2021-12-12 08:35 UTC, alstn2468 commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +3. 컴포넌트에서 reducer `사용하기`.
강조에서 코드블록으로 바꾸셨는데 의도하신 건가요?

2021-12-12 11:24 UTC, gnujoow requested changes
@alstn2468 께서 지적해주신 것처럼 원문의 markdown문법이 그대로 옮겨지지 않은 부분이 있습니다. 원문의 의도가 왜곡될 수 있기 때문에 원문의 문법을 유지해주세요

2021-12-12 11:24 UTC, gnujoow commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +3. 컴포넌트에서 reducer `사용하기`.
```suggestion
1. state를 설정하는 것에서 action을 dispatch 함수로 전달하는 것으로 **바꾸기**.
2. reducer 함수 **작성하기**.
3. 컴포넌트에서 reducer **사용하기**.
```

2021-12-12 11:24 UTC, gnujoow commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +현재 이벤트 핸들러는 state를 설정함으로써 `무엇을 할 것인지`를 명시합니다.
```suggestion
현재 이벤트 핸들러는 state를 설정함으로써 *무엇을 할 것인지* 를 명시합니다.
```

2021-12-12 11:24 UTC, gnujoow commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +  // React가 설정하게될 다음 state 값을 반환.
```suggestion
  // React가 설정하게될 다음 state 값을 반환합니다.
```

2021-12-12 11:31 UTC, jinsunee commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +3. 컴포넌트에서 reducer `사용하기`.
감사합니다! 리뷰 반영했습니다 [d006131](https://github.com/reactjs/ko.reactjs.org/pull/391/commits/d00613153665f80185d83adabd2170d037aa944b)

2021-12-12 11:38 UTC, jinsunee commented on beta/src/pages/learn/extracting-state-logic-into-a-reducer.md
> +  // React가 설정하게될 다음 state 값을 반환.
반영했습니다! [35474ef](https://github.com/reactjs/ko.reactjs.org/pull/391/commits/35474ef42c64a41f5fe00a42b8daf7d2b7d99b40)

2021-12-14 13:40 UTC, hg-pyun approved these changes
@alstn2468  @gnujoow 문제없으면 Approve 하고 CI 돌려보겠습니다 🙇

2021-12-14 14:28 UTC, gnujoow approved these changes
LGTM

2021-12-14 15:41 UTC, alstn2468 submitted a review, later dismissed

2021-12-14 16:04 UTC, taehwanno approved these changes

2021-12-14 16:05 UTC, merged

2021-12-14 16:05 UTC, taehwanno commented
자잘한 부분 몇 가지 직접 수정했습니다. 기여해주셔서 감사합니다!

2021-12-14 16:11 UTC, jinsunee commented
@taehwanno 앗 감사합니다🙏