:pencil: State As a Snapshot 번역 1차
reactjs/ko.reactjs.org pull request #396
Opened 2021-12-14 11:00 UTC by h2ck4u

## Progress

- [ ] 번역 초안 작성 (Draft translation)
- [ ] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [ ] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [ ] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [ ] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2021-12-14 12:53 UTC, h2ck4u commented on beta/src/pages/learn/state-as-a-snapshot.md
> -In React, it works a little differently from this mental model. On the previous page, you saw that [setting state requests a re-render](/learn/render-and-commit#step-1-trigger-a-render) from React. T
`it works a little differently from this mental model` 이 부분에서 mental model의 해석에 어려움이 있었습니다.

2021-12-14 12:56 UTC, h2ck4u commented on beta/src/pages/learn/state-as-a-snapshot.md
> -You can also visualize this by mentally substituting state variables with their values in your code. Since the `number` state variable is `0` for *this render*, its event handler looks like this:
`You can also visualize this by mentally substituting state variables with their values in your code`
이 부분에서 `by mentally substituting`의 번역에 어려움이 있었습니다.
도움을 주시면 감사하겠습니다.

2021-12-14 12:56 UTC, h2ck4u commented on beta/src/pages/learn/state-as-a-snapshot.md
> -* You can mentally substitute state in event handlers, similarly to how you think about the rendered JSX.
You can mentally substitute state in event handlers
이 부분에서 mentally substitute state의 번역에 어려움이 있었습니다.
도움을 주시면 감사하겠습니다.

2021-12-16 15:19 UTC, gnujoow commented
PR 올려주셔서 감사합니다. 우선은 pr template에 있는 항목들을 모두 확인 해주시고 반영해주시면 감사하겠습니다. 
이를테면) state -> 상태로 옮겨주셧는데, 이는 [번역하면 안되는 용어](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary#%EB%B2%88%EC%97%AD%ED%95%98%EB%A9%B4-%EC%95%88%EB%90%98%EB%8A%94-%EC%9A%A9%EC%96%B4)에 해당합니다.

2021-12-22 14:14 UTC, hg-pyun commented on beta/src/pages/learn/state-as-a-snapshot.md
> +읽고 쓰는 State 변수는 일반적인 자바스크립트 변수처럼 보일 수 있습니다. 그러나 state는 스냅샷 처럼 작동합니다. state를 설정하여도 이미 가지고 있는 state는 변경되지 않고, 대신에 리 렌더링을 실행합니다.
```suggestion
읽고 쓰는 State 변수는 일반적인 자바스크립트 변수처럼 보일 수 있습니다. 그러나 state는 스냅샷 처럼 작동합니다. state를 설정하여도 이미 가지고 있는 state는 변경되지 않고, 대신에 다시 렌더링을 실행합니다.
```

2021-12-22 14:14 UTC, hg-pyun commented on beta/src/pages/learn/state-as-a-snapshot.md
> +* state 설정이 어떻게 리 렌더링을 실행하는지
```suggestion
* state 설정이 어떻게 다시 렌더링을 실행하는지
```

2021-12-22 14:14 UTC, hg-pyun commented on beta/src/pages/learn/state-as-a-snapshot.md
> +<Illustration alt="폼에서부터 제출버튼 위에 손가락에서 확인메세지까지의 선형 과정입니다." src="/images/docs/sketches/s_ui-response.jpg" />
선형 과정이란 단어가 직관적이지 않은 것 같아요. 좀 더 이해하기 쉬운 단어로 바꾸면 어떨까요?

2021-12-22 14:14 UTC, hg-pyun commented on beta/src/pages/learn/state-as-a-snapshot.md
> -In React, it works a little differently from this mental model. On the previous page, you saw that [setting state requests a re-render](/learn/render-and-commit#step-1-trigger-a-render) from React. T
`React에서 이것은 일반적인 예상과 조금 다르게 동작합니다.` 정도로 번역하면 어떨까요?

2021-12-22 14:14 UTC, hg-pyun commented on beta/src/pages/learn/state-as-a-snapshot.md
> -In React, it works a little differently from this mental model. On the previous page, you saw that [setting state requests a re-render](/learn/render-and-commit#step-1-trigger-a-render) from React. T
전체적으로 리 렌더링 보다는 `다시` 같은 한국어로 바꾸면 좋을 것 같습니다.

2021-12-22 14:14 UTC, hg-pyun commented on beta/src/pages/learn/state-as-a-snapshot.md
> +`알럿`은 다음과 같아야 합니다.
```suggestion
`경고창`은 다음과 같아야 합니다.
```

2021-12-22 14:14 UTC, hg-pyun commented on beta/src/pages/learn/state-as-a-snapshot.md
> +알럿을 `setWalk` 호출 전후에 배치하든 상관없이 차이가 없습니다. 렌더링의 `walk` 값은 고정되어 있습니다. `setWalk`를 호출하면 *다음* 렌더링에 대해서만 변경되지만, 이전 렌더링의 이벤트 핸들러에는 영향을 미치지 않습니다.
```suggestion
경고창을 `setWalk` 호출 전후에 배치하든 상관없이 차이가 없습니다. 렌더링의 `walk` 값은 고정되어 있습니다. `setWalk`를 호출하면 *다음* 렌더링에 대해서만 변경되지만, 이전 렌더링의 이벤트 핸들러에는 영향을 미치지 않습니다.
```

2021-12-23 14:06 UTC, h2ck4u commented on beta/src/pages/learn/state-as-a-snapshot.md
> +<Illustration alt="폼에서부터 제출버튼 위에 손가락에서 확인메세지까지의 선형 과정입니다." src="/images/docs/sketches/s_ui-response.jpg" />
`폼에서부터 제출버튼 위에 손가락을 대고 있는 모습 그리고 확인메세지까지의 진행 과정입니다.`로 수정해보았습니다.

2021-12-27 14:58 UTC, hg-pyun submitted a review, later dismissed

2021-12-27 14:58 UTC, hg-pyun commented
@gnujoow 님 최종 컨펌을 기다려봅니다.

2022-01-06 09:01 UTC, gnujoow requested changes
line diff가 잇는것 같습니다. 원문의 경우 443행인데 번역후에는 444행이네요 line diff만 해결해주시면 나머지는 좋은것 같습니다 감사합니다.

2022-01-06 13:37 UTC, h2ck4u commented
@gnujoow 
해결하였습니다 감사합니다 : )

2022-01-11 19:32 UTC, gnujoow approved these changes

2022-01-14 13:15 UTC, merged