Translate: conditional-rendering
reactjs/ko.reactjs.org pull request #399
Opened 2021-12-19 03:25 UTC by devdubby

## Progress

- [ ] 번역 초안 작성 (Draft translation)
- [ ] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [ ] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [ ] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [ ] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2021-12-19 03:29 UTC, devdubby commented
몇몇 번역투? 의 어색한 문장들이 있는데 먼저 PR을 남깁니다. 한번 확인 후 수정사항 제안해주시면 너무나 감사하겠습니다!

2021-12-19 03:30 UTC, devdubby commented on beta/src/pages/learn/conditional-rendering.md
> -If you're coming from an object-oriented programming background, you might assume that the two examples above are subtly different because one of them may create two different "instances" of `<li>`.
like blueprints 를 어떻게 번역할지 조금 고민했는데 그냥 "청사진" 이라고 번역해도 괜찮을까요?

2021-12-19 03:32 UTC, devdubby commented on beta/src/pages/learn/conditional-rendering.md
> -When the shortcuts get in the way of writing plain code, try using an `if` statement and a variable. You can reassign variables defined with [`let`](https://developer.mozilla.org/en-US/docs/Web/JavaS
여기서 shortcuts 을 번역하는데 고민이 많았습니다. 문맥상 위에서 설명했던 코드 작성 방법을 shortcuts 라고 하는것 같아 "위와 같은 방법" 이라고 번역했는데 괜찮을까요?

2021-12-19 03:34 UTC, devdubby commented on beta/src/pages/learn/conditional-rendering.md
> -Another common shortcut you'll encounter is the [JavaScript logical AND (`&&`) operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND#:~:text=The%20logical%
여기서의 shortcut 번역도 조금 고민이 되었는데 "손쉬운 방법" 으로 번역해도 괜찮을까요?

2021-12-22 14:07 UTC, hg-pyun commented
바뻐서 리뷰를 못하고있네요 8ㅅ8;; 주말에 시간내서 보겠습니다. 번역 감사합니다 🙇

2022-01-06 09:09 UTC, gnujoow requested changes
원문과 line수가 다른것 같습니다 확인 한번 부탁드립니다.

2022-01-06 09:09 UTC, gnujoow commented on beta/src/pages/learn/conditional-rendering.md
> +짐을 쌌으면 표시 할 수 있는 여러 개의 `Item`을 렌더링하는 `PackingList` 컴포넌트가 있다고 가정해보세요.
```suggestion
짐을 챙겼는지 안챙겼는지 표시할 수 있는  여러 개의 `Item`을 렌더링하는 `PackingList` 컴포넌트가 있다고 가정해보세요.
```
which can be marked as packed or not 의 원문의 의미를 더 상세하게 옮기는것이 이해하기 더 좋은것 같습니다.

2022-01-06 09:09 UTC, gnujoow commented on beta/src/pages/learn/conditional-rendering.md
> +`Item` 컴포넌트 중 일부는 `isPacked` 프로퍼티가 `false`가 아닌 `true`로 설정되어 있습니다. `isPacked={true}`인 경우 짐을 싼 항목에 체크 표시(✔)를 추가하려고 합니다.
props는 번역하지 않는 용어입니다. 아래 문서를 확인 해주세요
https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary#%EB%B2%88%EC%97%AD%ED%95%98%EB%A9%B4-%EC%95%88%EB%90%98%EB%8A%94-%EC%9A%A9%EC%96%B4

2022-01-06 09:09 UTC, gnujoow commented on beta/src/pages/learn/conditional-rendering.md
> +이 중복코드가 나쁘지는 않지만, 코드를 유지 보수하기 더 어렵게 만들 수 있습니다. `className`을 바꾸고 싶다면? 코드상 두 군데를 수정해야 합니다! 이러한 상황에서 조건부로 약간의 JSX를 포함해 코드를 더 [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) 하게 만들 수 있습니다.
```suggestion
이 중복코드가 나쁘지는 않지만, 코드를 유지 보수하기 더 어렵게 만들 수 있습니다. `className`을 바꾸고 싶다면? 코드상 두 군데를 수정해야 합니다! 이러한 상황에서 조건부로 약간의 JSX를 포함해 코드를 더 [DRY (don't repeat yourself)](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) 하게 만들 수 있습니다.
```

dry가 약어라서 이렇게 풀어서 설명하면 이해하기 더 좋을것 같은데 어떻게 생각하시나요

2022-01-22 14:16 UTC, hg-pyun commented
@devdubby 코멘트 확인한번 부탁드립니다 🙇

2022-01-22 15:24 UTC, devdubby commented
@hg

2022-01-22 15:42 UTC, devdubby commented on beta/src/pages/learn/conditional-rendering.md
> +이 중복코드가 나쁘지는 않지만, 코드를 유지 보수하기 더 어렵게 만들 수 있습니다. `className`을 바꾸고 싶다면? 코드상 두 군데를 수정해야 합니다! 이러한 상황에서 조건부로 약간의 JSX를 포함해 코드를 더 [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) 하게 만들 수 있습니다.
네 그러는게 더 좋겠네요! 코멘트 감사합니다.

2022-01-22 16:12 UTC, devdubby commented
@hg-pyun @gnujoow 
에고... 저번에 리뷰 해주신거 봤는데 이제야 수정 했네요...! 리뷰해주신 내용 모두 반영하여 다시 업데이트 했습니다..! 감사합니다 👍

2022-02-15 12:58 UTC, gnujoow approved these changes

2022-02-25 02:15 UTC, merged