Translate passing data deeply with context
reactjs/ko.reactjs.org pull request #400
Opened 2021-12-19 07:21 UTC by Jincy7

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [ ] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [ ] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [ ] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [ ] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2021-12-20 06:28 UTC, gnujoow requested changes
변경이력을 정확히 확인할 수 있도록 line diff가 차이나지 않도록 수정 부탁드려요

2021-12-20 06:28 UTC, gnujoow commented on beta/src/pages/learn/passing-data-deeply-with-context.md
> +title: Context 를 사용해 데이터 깊게 전달하기
```suggestion
title: Context를 사용해 데이터 깊게 전달하기
```

2021-12-22 14:06 UTC, hg-pyun commented
체크리스트도 확인 부탁드립니다! 혹시 적용이 되었다면 `checked` 상태로 부탁드려요! 🙇 
![image](https://user-images.githubusercontent.com/10627668/147105093-b401edcd-93df-4312-8041-a24cdf534bce.png)

2022-01-22 15:54 UTC, gnujoow requested changes
문서 곳곳에 읽었을때 부자연스러운 부분이 있는것 같습니다. 번역을 제안해주신 문장들을 다시 한번 살펴봐주시고 읽었을때 자연스러운 표현을 수정을 요청드립니다.

---

pass가 전달하다 넘기다 두가지 표현으로 작성된것 같습니다. 한가지로 통일하면 좋을것 같습니다.

2022-01-22 15:54 UTC, gnujoow commented on beta/src/pages/learn/passing-data-deeply-with-context.md
> +title: Context를 사용해 데이터 깊게 전달하기
```suggestion
title: Context를 사용해 데이터를 깊게 전달하기
```

2022-01-22 15:54 UTC, gnujoow commented on beta/src/pages/learn/passing-data-deeply-with-context.md
> +title: Context를 사용해 데이터 깊게 전달하기
조사가 포함되는것이 더 자연스러운것 같아 수정 제안합니다.

2022-01-22 15:54 UTC, gnujoow commented on beta/src/pages/learn/passing-data-deeply-with-context.md
> +흔히 부모 컴포넌트에서 자식 컴포넌트로 props를 통해 정보를 전달합니다. 하지만 props를 넘기는 것은 중간에 많은 컴포넌트를 거쳐야 하거나 애플리케이션의 많은 컴포넌트에서 동일한 정보가 필요한 경우에 장황하고 불편할 수 있습니다. Context를 사용하면  명시적으로 props를 넘겨주지 않아도 부모 컴포넌트가 트리에 있는 어떤 자식 컴포넌트에서나
```suggestion
보통의 경우 부모 컴포넌트에서 자식 컴포넌트로 props를 통해 정보를 전달합니다. 그러나 중간에 많은 컴포넌트를 거쳐야 하거나, 애플리케이션의 많은 컴포넌트에서 동일한 정보가 필요한 경우에는 props를 넘기는 것이 번거롭고 불편할 수 있습니다. Context를 사용하면  명시적으로 props를 넘겨주지 않아도 부모 컴포넌트가 트리에 있는 어떤 자식 컴포넌트에서나 (얼마나 깊게 있든지 간에) 정보를 사용할 수 있습니다.
```
제안) 흔히는 often에 의미가 더 가까운것 같습니다.  수정을 제안합니다.
의견) verbose가 장황하게~라는 의미가 있지만 번거롭다는게 좀더 자연스러운것 같은데 어떻게 생각하시나요?

2022-01-22 15:54 UTC, gnujoow commented on beta/src/pages/learn/passing-data-deeply-with-context.md
> +데이터를 사용할 트리안의 컴포넌트에 props를 전달하는 대신 "순간이동"시킬 방법이 있다면 좋지 않을까요? React의 context 기능으로 가능합니다!
```suggestion
데이터를 사용할 트리안의 컴포넌트에 props를 전달하는 대신 "순간이동"시킬 방법이 있다면 좋지 않을까요? React의 context를 사용하면 됩니다!
```
의견) 표현을 좀더 자연스럽게 변경해보았는데 어떻게 생각하시나요?

2022-01-22 15:54 UTC, gnujoow commented on beta/src/pages/learn/passing-data-deeply-with-context.md
> +Context는 부모 컴포넌트가 트리 상 아래에 있는 모든 곳에 데이터를 전달할 수 있도록 해줍니다. Context에는 많은 용도가 있습니다. 하나의 예시로 다음의 크기 조정을 위해 `level`을 받는  `Heading` 컴포넌트를 보세요.
```suggestion
Context는 부모 컴포넌트가 트리 상 아래에 있는 모든 곳에 데이터를 전달할 수 있도록 해줍니다. Context에는 많은 용도가 있습니다. 하나의 예시로 다음의 크기 조정을 위해 `level`을 받는  `Heading` 컴포넌트를 보세요.
```
수정제안) 트리 상 아래에 있다는 표현이 어색하게 들립니다. 다른 표현으로 수정 부탁드려요.

2022-01-22 15:54 UTC, gnujoow commented on beta/src/pages/learn/passing-data-deeply-with-context.md
> +이제 `Heading`과 `Section` 모두 자신들이 얼마나 "깊이" 있는지 확인하기 위해 `LevelContext`를 읽어 들입니다. 그리고 `Section`은 그 안에 있는 어떤 것이든 "더 깊은" 레벨이라는 것을 명시하기 위해 자식들을 `LevelContext`로 감싸고 있습니다.
```suggestion
이제 `Heading`과 `Section` 모두 자신들이 얼마나 "깊이" 있는지 확인하기 위해 `LevelContext`를 읽습니다. 그리고 `Section`은 그 안에 있는 어떤 것이든 "더 깊은" 레벨이라는 것을 명시하기 위해 자식들을 `LevelContext`로 감싸고 있습니다.
```

2022-01-23 15:24 UTC, Jincy7 commented on beta/src/pages/learn/passing-data-deeply-with-context.md
> +title: Context를 사용해 데이터 깊게 전달하기
좋은 제안 감사합니다 :) 반영하겠습니다.

2022-01-23 15:24 UTC, Jincy7 commented on beta/src/pages/learn/passing-data-deeply-with-context.md
> +흔히 부모 컴포넌트에서 자식 컴포넌트로 props를 통해 정보를 전달합니다. 하지만 props를 넘기는 것은 중간에 많은 컴포넌트를 거쳐야 하거나 애플리케이션의 많은 컴포넌트에서 동일한 정보가 필요한 경우에 장황하고 불편할 수 있습니다. Context를 사용하면  명시적으로 props를 넘겨주지 않아도 부모 컴포넌트가 트리에 있는 어떤 자식 컴포넌트에서나
'번거롭다'도 자연스러워서 좋은 번역인것 같습니다.

그런데 '장황하다' 로 번역한 것은 원글에서 코드가 길어진다는 의미로 사용된 듯 하여 의미를 살려 보고자 한 것도 있고,
번거롭고 불편하다는 표현이 의미가 중복되는 듯 해서 고민이 되네요.. 🤔

2022-01-23 15:24 UTC, Jincy7 commented on beta/src/pages/learn/passing-data-deeply-with-context.md
> +Context는 부모 컴포넌트가 트리 상 아래에 있는 모든 곳에 데이터를 전달할 수 있도록 해줍니다. Context에는 많은 용도가 있습니다. 하나의 예시로 다음의 크기 조정을 위해 `level`을 받는  `Heading` 컴포넌트를 보세요.
`Context는 부모 컴포넌트가 그 아래의 트리 전체에 데이터를 전달할 수 있도록 해줍니다.`

위와 같이 수정하면 좀 더 자연스러운 것 같습니다. 어떻게 생각하시나요?

2022-02-03 08:08 UTC, gnujoow commented on beta/src/pages/learn/passing-data-deeply-with-context.md
> +Context는 부모 컴포넌트가 트리 상 아래에 있는 모든 곳에 데이터를 전달할 수 있도록 해줍니다. Context에는 많은 용도가 있습니다. 하나의 예시로 다음의 크기 조정을 위해 `level`을 받는  `Heading` 컴포넌트를 보세요.
@Jincy7 좋은것 같습니다.

2022-04-05 13:22 UTC, hg-pyun approved these changes

2022-05-22 01:11 UTC, merged