Translate scaling up with reducer and context
reactjs/ko.reactjs.org pull request #404
Opened 2022-01-05 14:52 UTC by cos22k

## Progress

- [ ] 번역 초안 작성 (Draft translation)
- [ ] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [ ] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [ ] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [ ] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2022-01-11 19:33 UTC, gnujoow approved these changes

2022-01-11 19:33 UTC, gnujoow commented on beta/src/pages/learn/scaling-up-with-reducer-and-context.md
> +예를 들어, 아래 `TaskBoard` 컴포넌트에서 `TaskList` 컴포넌트로 tasks 리스트와 이벤트 핸들러를 전달합니다.:
```suggestion
예를 들어, 아래 `TaskBoard` 컴포넌트에서 `TaskList` 컴포넌트로 tasks 리스트와 이벤트 핸들러를 전달합니다.
```

2022-01-14 13:26 UTC, gnujoow requested changes
파일의 line diff가 존재합니다. 이부분 수정을 부탁드려요

2022-01-14 13:26 UTC, gnujoow commented on beta/src/pages/learn/scaling-up-with-reducer-and-context.md
> +## reducer와 context를 결합하기 {/*combining-a-reducer-with-context*/}
```suggestion
## Reducer와 context를 결합하기 {/*combining-a-reducer-with-context*/}
```

2022-01-14 13:26 UTC, gnujoow commented on beta/src/pages/learn/scaling-up-with-reducer-and-context.md
> +[reducer의 개요](/learn/extracting-state-logic-into-a-reducer)의 예시에서 reducer로 state를 관리하는 방법을 보았습니다. 해당 예시에서 state 업데이트 로직을 모두 포함하는 reducer 함수를 App.js 파일의 맨 아래에 선언했습니다.
```suggestion
[Reducer의 개요](/learn/extracting-state-logic-into-a-reducer)의 예시에서 reducer로 state를 관리하는 방법을 보았습니다. 해당 예시에서 state 업데이트 로직을 모두 포함하는 reducer 함수를 App.js 파일의 맨 아래에 선언했습니다.
```

2022-01-14 13:26 UTC, gnujoow commented on beta/src/pages/learn/scaling-up-with-reducer-and-context.md
> +지금처럼 간단한 예시에서는 괜찮지만, 10개나 100개의 컴포넌트를 거쳐 state나 함수를 전달하기는 쉽지 않습니다.
```suggestion
지금처럼 간단한 예시에서는 잘 동작하지만, 수십 수백개의 컴포넌트를 거쳐 state나 함수를 전달하기는 쉽지 않습니다.
```

2022-01-16 07:14 UTC, cos22k commented on beta/src/pages/learn/scaling-up-with-reducer-and-context.md
> +지금처럼 간단한 예시에서는 괜찮지만, 10개나 100개의 컴포넌트를 거쳐 state나 함수를 전달하기는 쉽지 않습니다.
훨씬 좋네요! 감사합니다 😀

2022-01-22 16:07 UTC, gnujoow requested changes
몇몇 문장들이 축약되어 옮겨진것 같습니다. 원문의 의미를 정확히 전달되면 더 좋을것 같아요

2022-01-22 16:07 UTC, gnujoow commented on beta/src/pages/learn/scaling-up-with-reducer-and-context.md
> +**`TaskBoard` 컴포넌트와 `TaskList` 컴포넌트는 하위 컴포넌트에 이벤트 핸들러를 전달하지 않습니다.** 각 컴포넌트에서 필요한 context를 읽을 수 있습니다.
`Task` 컴포넌트에 전달하는 내용이 빠져있습니다. `**The `TaskBoard` component does not pass any event handlers down, and the `TaskList` does not pass any event handlers to the `Task` component either` 가 축약된 형태로 번역되어 있는데 원문의 의미를 정확히 옮겨주시길 바랍니다.

2022-01-22 16:07 UTC, gnujoow commented on beta/src/pages/learn/scaling-up-with-reducer-and-context.md
> +필수적인 과정은 아니지만 reducer와 context를 모두 하나의 파일로 옮겨서 컴포넌트들을 조금 더 정리할 수 있습니다. 현재, `TasksContext.js`는 두 개의 context만을 선언하고 있습니다.
```suggestion
반드시 이런 방식으로 작성하지 않아도 되지만,  reducer와 context를 모두 하나의 파일에 작성하면 컴포넌트들을 조금 더 정리할 수 있습니다. 현재, `TasksContext.js`는 두 개의 context만을 선언하고 있습니다.
```
의견) reducer와 context를 한 파일에 작성하는 것이므로 과정으로 표현하기에는 큰 작업으로 느껴집니다. 위와 같이 옮겨보았는데 의견을 여쭙고 싶습니다.

2022-01-22 16:07 UTC, gnujoow commented on beta/src/pages/learn/scaling-up-with-reducer-and-context.md
> +**이렇게 하면 `TaskBoard`가 깔끔해질 수 있습니다.**
`This removes all the complexity and wiring from your` 도 같이 옮겨주세요

2022-02-02 07:33 UTC, hg-pyun approved these changes
LGTM

2022-02-02 07:34 UTC, hg-pyun requested changes
피드백이 반영 될 때까지 pending

2022-02-03 08:10 UTC, gnujoow reviewed
correct missing line diff

2022-02-03 08:10 UTC, gnujoow commented on beta/src/pages/learn/scaling-up-with-reducer-and-context.md
> +task 리스트를 업데이트하기 위해서 컴포넌트에서 context의 `dispatch` 함수를 읽고 호출할 수 있습니다.
```suggestion
task 리스트를 업데이트하기 위해서 컴포넌트에서 context의 `dispatch` 함수를 읽고 호출할 수 있습니다.

```

2022-02-03 08:10 UTC, gnujoow approved these changes
LGTM

2022-03-10 02:10 UTC, merged