feat: passing-props-to-a-component 번역 완료
reactjs/ko.reactjs.org pull request #478
Opened 2022-06-22 12:05 UTC by kmin-jeong

## Progress

- [ ] 번역 초안 작성 (Draft translation)
- [ ] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [ ] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [ ] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [ ] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2022-06-22 12:08 UTC, kmin-jeong commented
@hg-pyun  
할당된 passing-props-to-a-component 번역 완료했습니다!
어색한 부분 있으면 바로 고치겠습니다

2022-06-25 16:18 UTC, hg-pyun commented
@kmin-jeong 감사합니다.

2022-06-28 06:36 UTC, gnujoow requested changes
다음 문서들을 확인해주세요
- [ ]  https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation
- [ ] https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary

2022-06-28 06:36 UTC, gnujoow commented on beta/src/pages/learn/passing-props-to-a-component.md
> +title: 컴포넌트로 Props 전달하기
```suggestion
title: 컴포넌트에 Props 전달하기
```

2022-06-28 06:36 UTC, gnujoow commented on beta/src/pages/learn/passing-props-to-a-component.md
> +
```suggestion
React 컴포넌트는 다른 컴포넌트와 통신할 때 **props**를 사용합니다. 모든 부모 컴포넌트는 자식컴포넌트에게 그들의 props를 전달할 수 있습니다. props는 사용자에게 html 속성을 사용하게 할 뿐만 아니라, 캑체,배열 그리고 함수 를 포함하여 자바스크립트 value값도 함께 사용하게 합니다.
```

- line diff가 차이나지 않게 유지해주세요
- 번역투의 문장이 있습니다 좀더 자연스러운 문장으로 다듬어주세요

2022-06-28 06:36 UTC, gnujoow commented on beta/src/pages/learn/passing-props-to-a-component.md
> +
```suggestion
```

2022-07-14 03:13 UTC, dev-hikun commented on beta/src/pages/learn/passing-props-to-a-component.md
> +이제 당신은 `Avatar` 컴포너트 안에 있는 props를 읽어올 수 있습니다.
`컴포너트` -> `컴포넌트` 오타가 있습니다.

2022-07-14 03:16 UTC, dev-hikun commented on beta/src/pages/learn/passing-props-to-a-component.md
> +`Avartar`에 약간의 로직을 더할 때, `person`,`size` props는 랜더링 할 때 사용합니다.
`랜더링` -> `렌더링`으로 수정이 필요할 듯 합니다.

2022-07-14 03:16 UTC, dev-hikun commented on beta/src/pages/learn/passing-props-to-a-component.md
> +이제 `Avartar` 에서 서로 다른 props들과 다른 방식들로 랜더링 하는 것을 구성할 수 있습니다. 당신이 보기에 아슬아슬한 부분을 고쳐라!
`Avartar` -> `Avarter` 오타가 있습니다.

2022-08-21 09:13 UTC, kmin-jeong commented
@gnujoow @hg-pyun @dev-hikun  
merge가 된걸로 알고 있었는데 다시 열린걸 지금 발견했습니다
수정사항 전부 고쳤습니다. 확인 바랍니다!

2022-08-21 10:21 UTC, kmin-jeong commented
> 다음 문서들을 확인해주세요
> 
> * [ ]   https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation
> * [ ]  https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary

-> 확인하고 수정했습니다! 여기는 코멘트에 resolve가 안보여서 댓글도 남깁니다!

2022-08-21 13:21 UTC, dev-hikun commented on beta/src/pages/learn/passing-props-to-a-component.md
> +당신은 *당신만의* 컴포넌트에 어떠한 props든 전달해줄 수 있습니다.여기 예시를 보며 알아보자!
원 문장은 1라인인데 해당 문장은 2라인이 되었어요

2022-08-21 13:21 UTC, dev-hikun commented on beta/src/pages/learn/passing-props-to-a-component.md
> +는 `<img>`태그에 정보를 전달하는 props들입니다.
여기도 2줄이 되어있는 것 같습니다.

2022-08-21 13:29 UTC, kmin-jeong commented on beta/src/pages/learn/passing-props-to-a-component.md
> +는 `<img>`태그에 정보를 전달하는 props들입니다.
줄맞춤 수정했습니다!

2022-08-21 13:42 UTC, kmin-jeong commented
@dev-hikun @hg-pyun  @gnujoow 확인하고 추가적으로 원문이랑 안맞는 줄맞춤을 발견해서 함께 수정했습니다!

2022-08-22 12:33 UTC, gnujoow requested changes
전반적인 line diff를 확인해주세요

2022-08-22 12:33 UTC, gnujoow commented on beta/src/pages/learn/passing-props-to-a-component.md
> +
```suggestion
```

2022-08-22 12:33 UTC, gnujoow commented on beta/src/pages/learn/passing-props-to-a-component.md
> +
```suggestion
```

2022-08-22 12:49 UTC, kmin-jeong commented
@gnujoow  line diff 수정했습니다! 더 수정해야할 부분이 있을까요?

2022-08-25 12:13 UTC, gnujoow commented
@kmin-jeong 
<img width="913" alt="image" src="https://user-images.githubusercontent.com/10865414/186661157-274849bb-b183-4f29-9261-d08542a94183.png">
문서 마지막을 보면 불필요한 newline이 추가되어  line diff가 많은것을 확인 할 수 있습니다. 전반적으로 수정 부탁드립니다.

2022-08-26 11:29 UTC, gnujoow commented
> @gnujoow 혹시 위에 첨부해주신 사진처럼 어떻게 볼 수 있는지 여쭤봐도 될까요?

https://github.com/reactjs/ko.reactjs.org/pull/478/files
위 주소를 확인하시면 됩니다.

2022-09-07 14:28 UTC, gnujoow approved these changes
PR템플릿에 있는 문서링크를 천천히 다시 읽어주신뒤 문서 전반 수정 부탁드립니다.

2022-09-07 14:28 UTC, gnujoow commented on beta/src/pages/learn/passing-props-to-a-component.md
> +당신은 props를 "knobs(노브,문을 여닫기 위한 둥근 손잡이)" 생각하고 있을 것입니다. 함수 안에서 인자와 같은 역할을 맡지만 사실은, 오직 한 컴포넌트 안에서만 그 역할을 맡는다! React 컴포넌트 함수들은 `props`라는 객체의 한 개의 인자를 가지고 있습니다:
https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation#%EC%8C%8D%EC%A0%90%EC%9D%80-%EA%B1%B0%EC%9D%98-%EC%82%AC%EC%9A%A9%ED%95%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4

쌍점은 거의 사용하지 않습니다.

2022-09-07 14:52 UTC, kmin-jeong commented on beta/src/pages/learn/passing-props-to-a-component.md
> +당신은 props를 "knobs(노브,문을 여닫기 위한 둥근 손잡이)" 생각하고 있을 것입니다. 함수 안에서 인자와 같은 역할을 맡지만 사실은, 오직 한 컴포넌트 안에서만 그 역할을 맡는다! React 컴포넌트 함수들은 `props`라는 객체의 한 개의 인자를 가지고 있습니다:
@gnujoow 제가 쌍점을 넣은 이유가 원문에서 쌍점이 있는 부분들만 추가를 했었는데, 그러면 원문에 있더라도 쌍점은 안쓰는게 좋을까요?

2022-09-08 15:25 UTC, kmin-jeong commented
@hg-pyun @gnujoow @dev-hikun 위에서 지적하주신 부분들 수정했습니다. 혹시 지금도 지적해야할 부분이 보이면 지금은 일단 고친부분까지 머지하고 하고 다음에 이 부분에 기여해주실분이 더 작업하시는건 어떨까요?

2022-09-17 07:04 UTC, kmin-jeong commented
@gnujoow  혹시 제가 더 수정해야할 부분이 있을까요?

2022-09-26 09:07 UTC, kmin-jeong commented
@gnujoow @hg-pyun @dev-hikun
어색한 부분들 고치고 맞춤법 검사기를 돌렸습니다!
리뷰 요청하고 싶은데 한사람을 누르면 한사람이 제거 되네요ㅠㅠ 시간되실 때 확인 부탁드려요!

2022-10-16 04:05 UTC, gnujoow requested changes
다음 내용에 대해서 수정을 요청드립니다.

- [ ] 제목 뒤에 {/* */} 주석들이 잇는 부분들이 있습니다. 이부분을 원문과 동일하게 변경해주세요
- [ ] 의미 전달이 잘못된 문장들이 많습니다. 동사와 조사에 유의해서 원문의 의미가 정확하게 전달될 수 있도록 수정해주세요

두번째 수정 사항에 대해서는 제가 #100번째 라인까지 살펴보았는데 그 아래 부분에 대해서는 @kmin-jeong 님께 부탁드리겠습니다.

2022-11-12 14:35 UTC, kmin-jeong commented
@gnujoow  주어,조사와 바뀐 부분들과, 번역이 매끄럽게 이루어지지 않은 부분들 수정,맞춤법 검수 완료했습니다. 어색한 부분들 보이는건 전부 고쳤는데, 여전히 어색한 부분이 있다면 말씀해주세요.  200번째 줄 이하더라도 번역이 이상한 부분이 보여서 수정을 했습니다. 혹시 바뀌기 전이 낫다면 말씀해주세요!

2023-02-04 15:03 UTC, MaxKim-J commented
안녕하세요!
React docs 한국어 번역을 재개하기 위해 beta docs와 최신 문서들을 현 레포지토리에 반영하고, 번역 가이드라인을 재정비하는 중입니다. 일단의 정리를 위해 현재 열려있는 PR은 닫으려고 하니 양해 부탁드리고, 새로운 가이드라인에 맞춰 PR을 다시 올려주시면 감사하겠습니다. :)

2023-02-04 15:03 UTC, closed without merging