chore: Add Korean translation for React Top-Level API Docs
reactjs/ko.reactjs.org pull request #517
Opened 2022-10-24 13:37 UTC by hayeon9826

Add Korean translation for React Top-Level API Docs

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [ ] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2022-10-25 13:47 UTC, gnujoow commented
PR감사합니다. 빠른 시일내에 리뷰할게요!

2022-11-03 11:52 UTC, gnujoow requested changes
@hayeon9826 line diff한번 확인 부탁드릴게요. 원문과 같은 라인을 유지하도록 수정해주세요.

2022-12-30 02:41 UTC, hg-pyun approved these changes

2023-01-03 12:54 UTC, gnujoow approved these changes

2023-01-03 12:54 UTC, merged