chore: Add Korean translation for React Hooks API Reference Docs
reactjs/ko.reactjs.org pull request #518
Opened 2022-10-28 18:15 UTC by hayeon9826

Add Korean translation for React Hooks API Reference Docs

## Progress

- [x] 번역 초안 작성 (Draft translation)
- [x] [공통 스타일 가이드 확인 (Check the common style guide)](https://github.com/reactjs/ko.reactjs.org/blob/master/UNIVERSAL-STYLE-GUIDE.md)
- [x] [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation)
- [x] [용어 확인 (Check the term)](https://github.com/reactjs/ko.reactjs.org/wiki/Translate-Glossary)
- [ ] [맞춤법 검사 (Spelling check)](http://speller.cs.pusan.ac.kr/)
- [ ] 리뷰 반영 (Resolve reviews)

2022-11-01 17:33 UTC, gnujoow requested changes
PR감사합니다. 제안해주신 내용 확인을 위해 line diff수정을 요청드립니다. 🙏

2022-11-01 17:33 UTC, gnujoow commented on content/docs/hooks-reference.md
> +#### state 갱신의 batch (일괄 처리) {#batching-of-state-updates}
```suggestion
#### State 갱신의 batch (일괄 처리) {#batching-of-state-updates}
```
영문이 맨 앞에 오는 경우 대문자로 표현합니다.

2022-11-01 17:33 UTC, gnujoow commented on content/docs/hooks-reference.md
> +React 18부터 [모든 업데이트에 대해 일괄 처리가 기본적으로 활성화됩니다](/blog/2022/03/08/react-18-upgrade-guide.html#automatic-batching).
```suggestion
React 18 이전에는 React 이벤트 핸들러 내부의 업데이트만 일괄 처리되었습니다.

React 18부터 [모든 업데이트에 대해 일괄 처리가 기본적으로 활성화됩니다](/blog/2022/03/08/react-18-upgrade-guide.html#automatic-batching).
```
본문과 line diff 를 동일하게 하기 위해 개행을 추가합니다.

2022-11-01 17:33 UTC, gnujoow commented on content/docs/hooks-reference.md
> +DOM 업데이트를 강제로 동기식으로 적용해야 하는 경우는 드물지만, 이런 경우 [`flushSync`](/docs/react-dom.html#flushsync)를 적용할 수 있습니다. 그러나 이로 인해 성능이 저하될 수 있으므로 필요한 경우에만 수행하세요.
- [ ] 본문과 line diff가 발생하는데 한번 확인 부탁드려요

2022-11-01 17:33 UTC, gnujoow commented on content/docs/hooks-reference.md
> +
```suggestion
> 이는 `useEffect`에 전달된 함수가 호출되는 타이밍에만 영향을 미치며, 이러한 effect 내에서 예약된 업데이트는 여전히 지연됩니다. 이는 기능을 실행과 내부의 업데이트를 즉시 처리하는 `useLayoutEffect`와는 다릅니다.
```

2022-11-01 17:33 UTC, gnujoow commented on content/docs/hooks-reference.md
> +  // Memoizing은 query가 변경될 때가 아니라 deferredQuery가 변경될 때만 다시 렌더링하도록 합니다.
```suggestion
  // Memoizing은 query가 변경될 때가 아니라 
  // deferredQuery가 변경될 때만 다시 렌더링하도록 합니다.
```

2022-11-01 17:33 UTC, gnujoow commented on content/docs/hooks-reference.md
> +`startTransition` 을 사용하면 제공된 콜백의 업데이트를 transitions으로 표시할 수 있습니다:
```suggestion
`startTransition` 을 사용하면 제공된 콜백의 업데이트를 transitions으로 표시할 수 있습니다.
```

2022-11-02 08:13 UTC, hayeon9826 commented on content/docs/hooks-reference.md
> +예를 들어,  `id`를 필요한 요소에 직접 전달합니다:
@gnujoow 안녕하세요! 혹시 해당 변경사항에서 온점(.)이 아닌 쉼표(,)로 수정하면 되는게 맞을까요?

2022-11-02 08:19 UTC, hayeon9826 commented on content/docs/hooks-reference.md
> +`startTransition` 을 사용하면 제공된 콜백의 업데이트를 transitions으로 표시할 수 있습니다:
> PR감사합니다. 제안해주신 내용 확인을 위해 line diff수정을 요청드립니다. 🙏

@gnujoow 님 리뷰 감사합니다. 🙏 리뷰 해주신 곳 수정해서 적용했습니다. 확인 부탁드리겠습니다.

2022-11-03 11:47 UTC, gnujoow commented on content/docs/hooks-reference.md
> +예를 들어,  `id`를 필요한 요소에 직접 전달합니다:
@hayeon9826 네 맞습니다.아래 문서를 참고해주세요!
https://github.com/reactjs/ko.reactjs.org/wiki/Best-practices-for-translation#%EC%8C%8D%EC%A0%90%EC%9D%80-%EA%B1%B0%EC%9D%98-%EC%82%AC%EC%9A%A9%ED%95%98%EC%A7%80-%EC%95%8A%EC%8A%B5%EB%8B%88%EB%8B%A4

2022-11-03 11:51 UTC, gnujoow requested changes

2022-11-03 11:51 UTC, gnujoow commented on content/docs/hooks-reference.md
> +브라우저가 페인트를 칠할 때까지 `useEffect`가 연기되는 경우에도 새로운 렌더 전에 반드시 실행된다. React는 항상 새 업데이트를 시작하기 전에 이전 렌더의 effect를 실행합니다.
```suggestion
브라우저가 패인팅을 완료할 때까지 `useEffect`가 연기되는 경우에도 새로운 렌더 전에 반드시 실행됩니다. React는 항상 새 업데이트를 시작하기 전에 이전 렌더의 effect를 실행합니다.
```
여기서 paint는 색칠하다의 페인트보다는 렌더링 과정중에 하나인 pain인것 같습니다. 해서 원문을 그대로 옮깁니다.

https://web.dev/critical-rendering-path-render-tree-construction/

2022-11-03 11:51 UTC, gnujoow commented on content/docs/hooks-reference.md
> +
541행에 불필요한 개행이 있는것 같네요 삭제 부탁드립니다.

2022-11-07 08:10 UTC, gnujoow approved these changes

2023-02-04 15:02 UTC, MaxKim-J commented
안녕하세요!
React docs 한국어 번역을 재개하기 위해 beta docs와 최신 문서들을 현 레포지토리에 반영하고, 번역 가이드라인을 재정비하는 중입니다. 일단의 정리를 위해 현재 열려있는 PR은 닫으려고 하니 양해 부탁드리고, 새로운 가이드라인에 맞춰 PR을 다시 올려주시면 감사하겠습니다. :)

2023-02-04 15:02 UTC, closed without merging