translate note part in ensuring reusable state
reactjs/ko.reactjs.org pull request #524
Opened 2022-11-05 00:56 UTC by SeyoungJoo

예상치 못한 부작용 검사(Detecting unexpected side effects) 파트의 note 부분이 번역이 안되어있어 그 부분을 번역하였습니다.

2022-11-07 08:08 UTC, gnujoow requested changes
원문과 line diff를 동일하게 수정해주실 수 있을까요 @SeyoungJoo

2022-11-07 14:18 UTC, SeyoungJoo commented
수정하였습니다 🙂

2023-01-07 05:27 UTC, SeyoungJoo commented
@gnujoow 이 PR은 병합이 언제 될까요? 혹시 문제가 있어서 병합이 안되고 있는거면 알려주시면 감사하겠습니다-!

2023-02-04 15:01 UTC, MaxKim-J commented
안녕하세요!
React docs 한국어 번역을 재개하기 위해 beta docs와 최신 문서들을 현 레포지토리에 반영하고, 번역 가이드라인을 재정비하는 중입니다. 일단의 정리를 위해 현재 열려있는 PR은 닫으려고 하니 양해 부탁드리고, 새로운 가이드라인에 맞춰 PR을 다시 올려주시면 감사하겠습니다. :)

2023-02-04 15:01 UTC, closed without merging