translate react dom part
reactjs/ko.reactjs.org pull request #529
Opened 2022-11-07 21:20 UTC by SeyoungJoo

react dom파트의 미번역된 부분을 번역하였습니다.

2022-11-09 02:59 UTC, gnujoow requested changes

2022-11-09 02:59 UTC, gnujoow commented on content/docs/reference-react-dom.md
> +> React 18에서는 `render` 와 `hydrate`가 새로운 [client methods](/docs/react-dom-client.html)로 대체되었습니다. 이 메서드들은 앱이 마치 React 17을 실행하는 것처럼 행동할 것이라는 경고를 보낼 것입니다. (자세한 내용은 [여기]를 참조하세요(https://reactjs.org/link/sw
```suggestion
> React 18에서는 `render` 와 `hydrate`가 새로운 [client methods](/docs/react-dom-client.html)로 대체되었습니다. 이 메서드들은 앱이 마치 React 17을 실행하는 것처럼 행동할 것이라는 경고를 보낼 것입니다. (자세한 내용은 [여기](https://reactjs.org/link/switch-to-createroot)를 참조하세요).
```

2023-02-04 14:59 UTC, MaxKim-J commented
안녕하세요!
React docs 한국어 번역을 재개하기 위해 beta docs와 최신 문서들을 현 레포지토리에 반영하고, 번역 가이드라인을 재정비하는 중입니다. 일단의 정리를 위해 현재 열려있는 PR은 닫으려고 하니 양해 부탁드리고, 새로운 가이드라인에 맞춰 PR을 다시 올려주시면 감사하겠습니다. :)

2023-02-04 14:59 UTC, closed without merging

2023-02-09 00:01 UTC, SeyoungJoo commented
허허허.. 몇달동안 PR리뷰도 안되더니 이게 무슨..

2023-02-09 00:06 UTC, SeyoungJoo commented
몇달 동안 기다려도 기다려도 머지가 안돼서 뭐지 싶었는데 결국 이게 무슨.. 허허허 미리미리 좀 해주시지 황당하네요

2023-02-09 00:15 UTC, SeyoungJoo commented
허허허.. 몇달동안 기다려도 머지가 안되길래 뭐지 했는데 허허허..

2023-02-12 08:08 UTC, MaxKim-J commented
@SeyoungJoo 새로운 가이드라인은 현재 준비 중에 있습니다!